### ISSUE TITLE
UserInfo endpoint call failing with POST method

### ISSUE THREAD

**Issue by mandree95** [nordeck/jitsi-keycloak-adapter#2]
**Describe the bug**
Install the adapter and keycloak in version 20.0.5. Instead of successfuly retrieving the userinfo, a 401 error is thrown by the adapter. Also there is an exception message in the keycloak server log.

**Steps To Reproduce**
See above. Try to create a room, the call of the userinfo endpoint does not work properly.

**Expected behavior**
The problem is that the adapter makes a POST request to retrieve the UserInfo endpoint from Keycloak, but does not set a body or content type.

To fix the problem, the method must be changed from POST to GET: https://github.com/nordeck/jitsi-keycloak-adapter/blob/main/adapter.ts#L155

This is also recommended in the openid connect spec: https://openid.net/specs/openid-connect-core-1_0.html#UserInfoRequest

**Screenshots / Videos**
```
ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-53) Uncaught server error: java.lang.NullPointerException
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getFormParameters(BaseHttpRequest.java:53)
	at org.jboss.resteasy.plugins.server.BaseHttpRequest.getDecodedFormParameters(BaseHttpRequest.java:74)
	at jdk.internal.reflect.GeneratedMethodAccessor150.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:166)
	at com.sun.proxy.$Proxy45.getDecodedFormParameters(Unknown Source)
	at org.keycloak.protocol.oidc.endpoints.UserInfoEndpoint.issueUserInfoPost(UserInfoEndpoint.java:146)
	at jdk.internal.reflect.GeneratedMethodAccessor628.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
```

**Environment:**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by emrahcom** [comment]
Thank you for the detailed bug report. I think it is fixed now.
